#---------------------------------
# development mode => local環境
#---------------------------------
development:
  adapter: mysql2
  encoding: utf8
  database: web_medicine_notebook_development
  pool: 5
  username: root
  password: 
  collation: utf8_general_ci
  host: 127.0.0.1
  port: 3306